django-elk-main/django_elk/base_app/urls.py
from django.urls import path
from base_app import views

app_name = 'base_app'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('health/', views.HealthStatusView.as_view(), name='health-status'),
    path('add_city', views.CityAddView.as_view(), name='add-city'),
    path('list_city', views.CityListView.as_view(), name='list-city'),
]

django-elk-main/django_elk/django_elk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_app.urls', namespace='base_app')),
]

django-elk-main/django_elk/base_app/models.py
from django.db import models

# Create your models here.

django-elk-main/django_elk/base_app/forms.py
from django import forms

class CityAddForm(forms.Form):
    city_name = forms.CharField(label='City')
    city_population = forms.IntegerField(label='Population', min_value=1)

django-elk-main/django_elk/base_app/views.py
from django.conf import settings
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy
from datetime import datetime
from elasticsearch import Elasticsearch
from base_app.forms import CityAddForm

# Create your views here.
class Index(TemplateView):
    """ Default Landing Page """
    template_name = 'base_app/base_app_index.html'


class HealthStatusView(TemplateView):
    """ All Incident Dashboard """
    template_name = 'base_app/base_app_health_status.html'

    def get_context_data(self, **kwargs):
        context = super(HealthStatusView, self).get_context_data(**kwargs)
        context['health_status'] = 'OK'
        return context


class CityListView(TemplateView):
    """ All city List """
    template_name = 'base_app/base_app_city_list.html'

    def get_context_data(self, **kwargs):
        context = super(CityListView, self).get_context_data(**kwargs)
        es = Elasticsearch([settings.ELASTIC_ENDPOINT])
        result = es.search(index=settings.ELASTIC_INDEX_NAME, body={"query":{"match_all":{}}})
        city_dict = {}
        if result['hits']['hits']:
            for doc in result['hits']['hits']:
                city_dict[doc['_source']['city']] = doc['_source']['population']
        
        print(city_dict)
        context['city_dict'] = city_dict
        return context


class CityAddView(FormView):
    """ Add a new city """
    form_class = CityAddForm
    template_name = 'base_app/base_app_city_add_form.html'
    def get_success_url(self):
        return reverse_lazy('base_app:list-city')

    def form_valid(self, form):
        city = self.request.POST.get('city_name', False)
        population = self.request.POST.get('city_population', False)
        print(city)
        print(population)
        if False in [city, population]:
            print("Invalid input")
        else:
            es = Elasticsearch([settings.ELASTIC_ENDPOINT])
            doc = {
                'city': self.request.POST.get('city_name'),
                'population': self.request.POST.get('city_population'),
                'timestamp': datetime.now()
            }
            res = es.index(index=settings.ELASTIC_INDEX_NAME, id=city, document=doc)
            print(res)
        return super(CityAddView, self).form_valid(form)

django-elk-main/django_elk/base_app/templates/base_app/base_app_base.html
<html>
    <head>
        {% load static %}
        {# load django_simple_bulma #}
        {# bulma #}
        {# font_awesome #}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
        
        {% block extra_js %}
        {% endblock %}
        </head>
        <body>
            {# Navbar #}
            <nav class="navbar is-dark">
                <div class="navbar-brand">

                    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
        
                <div id="navbarExampleTransparentExample" class="navbar-menu">
                    <div class="navbar-start">
                        <a class="navbar-item" href="{% url 'base_app:index' %}">
                            Home
                        </a>
                        <div class="navbar-item has-dropdown is-hoverable">
                            <!-- <a class="navbar-link" href="/documentation/overview/start/"> -->
                            <a class="navbar-link">
                                Functions
                            </a>
                            <div class="navbar-dropdown is-boxed">
                                <a class="navbar-item" href="{% url 'base_app:health-status' %}">
                                    Health Status
                                </a>
                                <a class="navbar-item" href="{% url 'base_app:list-city' %}">
                                    List City
                                </a>
                                <a class="navbar-item" href="{% url 'base_app:add-city' %}">
                                    Add City
                                </a>
                            </div>
                        </div>
                    </div>
        
                    <div class="navbar-end">
                    </div>
                </div>
            </nav>
            {# Block to place page content #}
            {% block body_block %}
            {% endblock %}
        </body>
</html>

django-elk-main/django_elk/base_app/templates/base_app/base_app_city_add_form.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
    <section class="section">
        <form method="post">
            {% csrf_token %}
            <div class="field">
                <label for="{{ form.service.id_for_label }}">{{ form.city_name.label }}</label>
                <div class="control">
                        {{ form.city_name }}
                </div>
            </div>
            <div class="field">
                <label for="{{ form.kingdom.id_for_label }}">{{ form.city_population.label }}</label>
                <div class="control">
                        {{ form.city_population }}
                </div>
            </div>
            <div class="field is-grouped">
                <div class="control">
                  <button class="button is-normal is-info" type="submit" value="Submit">Submit</button>
                </div>
            </div>            
        </form>
    </section>
</div>
{% endblock %}

django-elk-main/django_elk/base_app/templates/base_app/base_app_city_list.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<div class="box">
    <table class="table">
        <thead>
            <tr>
                <td>City</td>
                <td>Population</td>
            </tr>
        </thead>
        <tbody>
            {% for city, population in city_dict.items %}
            <tr>
                <td>{{ city }}</td>
                <td>{{ population }}</td>
            </tr>
            {% empty %}
            <tr>
                <td>No Records found</td>
            </tr>                
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

django-elk-main/django_elk/base_app/templates/base_app/base_app_health_status.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
<div class="box">
    {{ health_status }}
</div>
{% endblock %}

django-elk-main/django_elk/base_app/templates/base_app/base_app_index.html
{% extends 'base_app/base_app_base.html' %}
{% load static %}
{% block body_block %}
    <section class="hero is-medium is-link" style="background: linear-gradient(-30deg, #243a5eE5, #243a5eE5 50%, #243a5e 45%) #fff;">
        <div class="hero-body has-text-centered">
        <p class="title">
            My App
        </p>
        </div>
    </section>

    <section class="section">
        
        </div>
    </section>
{% endblock %}